name: Build and Push Image

env:
  DEFAULT_RELEASE_VERSION: "v1.0.0"

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: tduarte #ubuntu-latest
    needs: helm-test
    outputs:
      release_tag: ${{ steps.bump-version.outputs.new_tag || env.DEFAULT_RELEASE_VERSION }}
      previous_tag: ${{ steps.bump-version.outputs.previous_tag || env.DEFAULT_RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_PUSH_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.DOCKER_PUSH_REPO }}/${{ vars.DOCKER_PUSH_IMAGE }}:latest
          context: .
